### Create a new message

POST http://localhost:3000/messages
content-type: application/json

{
    "content": "What's up buddy"
}

### Collecting all messages
GET http://localhost:3000/messages

### get specific message
GET http://localhost:3000/messages/8117